<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Carbon\Carbon;

class ArTrackingController extends Controller
{
    public function index()
    {
        // Dummy Data for UI Development
        // In production, this comes from API or Import
        $dummyInvoices = [
            // --- BATCHING ---
            [
                'id' => 1,
                'payer_name' => 'Admedika',
                'patient_name' => 'John Doe',
                'mrn' => '009988',
                'invoice_no' => '561000',
                'invoice_date' => '2026-02-10',
                'amount' => 1500000,
                'paid_amount' => 0,
                'balance' => 1500000,
                'due_days' => 0,
                'status' => 'BATCHING',
                'ref_no' => null,
                'courier_via' => null,
                'tracking_no' => null,
                'sent_date' => null,
                'received_date' => null,
                'paid_on' => null,
                'remarks' => 'Menunggu rincian obat dari apotek.',
                'is_cancelled' => false,
                'cancelled_date' => null,
            ],
            [
                'id' => 2,
                'payer_name' => 'Admedika',
                'patient_name' => 'Sarah Connor',
                'mrn' => '009990',
                'invoice_no' => '561005',
                'invoice_date' => '2026-03-01',
                'amount' => 3200000,
                'paid_amount' => 0,
                'balance' => 3200000,
                'due_days' => 0,
                'status' => 'BATCHING',
                'ref_no' => null,
                'courier_via' => null,
                'tracking_no' => null,
                'sent_date' => null,
                'received_date' => null,
                'paid_on' => null,
                'remarks' => null,
                'is_cancelled' => false,
                'cancelled_date' => null,
            ],
            // --- SENT ---
            [
                'id' => 3,
                'payer_name' => 'Global Excel',
                'patient_name' => 'Christopher Parr',
                'mrn' => '062215',
                'invoice_no' => '558653',
                'invoice_date' => '2025-12-24',
                'amount' => 1200000,
                'paid_amount' => 0,
                'balance' => 1200000,
                'due_days' => 30,
                'status' => 'SENT',
                'ref_no' => '25-JKT001',
                'courier_via' => 'JNE',
                'tracking_no' => '3592363150005',
                'sent_date' => '2026-01-03',
                'received_date' => null,
                'paid_on' => null,
                'remarks' => null,
                'is_cancelled' => false,
                'cancelled_date' => null,
            ],
            [
                'id' => 4,
                'payer_name' => 'Global Excel',
                'patient_name' => 'Christopher Parr',
                'mrn' => '062215',
                'invoice_no' => '558974',
                'invoice_date' => '2025-12-27',
                'amount' => 1180793,
                'paid_amount' => 0,
                'balance' => 1180793,
                'due_days' => 30,
                'status' => 'SENT',
                'ref_no' => '25-JKT002',
                'courier_via' => 'JNE',
                'tracking_no' => '3592363150005',
                'sent_date' => '2026-01-03',
                'received_date' => null,
                'paid_on' => null,
                'remarks' => null,
                'is_cancelled' => false,
                'cancelled_date' => null,
            ],
            [
                'id' => 5,
                'payer_name' => 'Global Excel',
                'patient_name' => 'Christopher Parr',
                'mrn' => '062215',
                'invoice_no' => '559321',
                'invoice_date' => '2025-12-31',
                'amount' => 1595658,
                'paid_amount' => 0,
                'balance' => 1595658,
                'due_days' => 30,
                'status' => 'SENT',
                'ref_no' => '25-JKT003',
                'courier_via' => 'JNE',
                'tracking_no' => '3590558460007',
                'sent_date' => '2026-01-31',
                'received_date' => null,
                'paid_on' => null,
                'remarks' => null,
                'is_cancelled' => false,
                'cancelled_date' => null,
            ],
            // --- SENT + CANCELLED ---
            [
                'id' => 6,
                'payer_name' => 'Global Excel',
                'patient_name' => 'Michael Torres',
                'mrn' => '062300',
                'invoice_no' => '559400',
                'invoice_date' => '2026-01-15',
                'amount' => 850000,
                'paid_amount' => 0,
                'balance' => 850000,
                'due_days' => 30,
                'status' => 'SENT',
                'ref_no' => '25-JKT010',
                'courier_via' => 'TIKI',
                'tracking_no' => '9988776655',
                'sent_date' => '2026-01-20',
                'received_date' => null,
                'paid_on' => null,
                'remarks' => 'Invoice cancelled - pasien pindah asuransi.',
                'is_cancelled' => true,
                'cancelled_date' => '2026-02-10',
            ],
            // --- RECEIVED ---
            [
                'id' => 7,
                'payer_name' => 'Admedika',
                'patient_name' => 'Maria Garcia',
                'mrn' => '009991',
                'invoice_no' => '560100',
                'invoice_date' => '2026-01-05',
                'amount' => 4500000,
                'paid_amount' => 0,
                'balance' => 4500000,
                'due_days' => 45,
                'status' => 'RECEIVED',
                'ref_no' => '26-ADM001',
                'courier_via' => 'Pos Indonesia',
                'tracking_no' => 'POS123456789',
                'sent_date' => '2026-01-10',
                'received_date' => '2026-01-15',
                'paid_on' => null,
                'remarks' => 'Menunggu review dari pihak asuransi.',
                'is_cancelled' => false,
                'cancelled_date' => null,
            ],
            // --- REVISE ---
            [
                'id' => 8,
                'payer_name' => 'Admedika',
                'patient_name' => 'Jane Smith',
                'mrn' => '009989',
                'invoice_no' => '561001',
                'invoice_date' => '2026-02-12',
                'amount' => 2500000,
                'paid_amount' => 0,
                'balance' => 2500000,
                'due_days' => 30,
                'status' => 'REVISE',
                'ref_no' => '25-JKT008',
                'courier_via' => 'JNE',
                'tracking_no' => '3590558460009',
                'sent_date' => '2026-02-15',
                'received_date' => '2026-02-20',
                'paid_on' => null,
                'remarks' => 'Invoice dikembalikan karena salah tarif.',
                'is_cancelled' => false,
                'cancelled_date' => null,
            ],
            // --- PAID ---
            [
                'id' => 9,
                'payer_name' => 'Global Excel',
                'patient_name' => 'Edward Gareth Andrews',
                'mrn' => '007403',
                'invoice_no' => '516339',
                'invoice_date' => '2024-09-02',
                'amount' => 3604561,
                'paid_amount' => 3604561,
                'balance' => 0,
                'due_days' => 30,
                'status' => 'PAID',
                'ref_no' => '24-JKT004',
                'courier_via' => 'JNE',
                'tracking_no' => '3578056480000',
                'sent_date' => '2024-09-06',
                'received_date' => '2024-09-10',
                'paid_on' => '2024-10-23',
                'remarks' => 'Ditelepon tanggal 15, kata asuransi sedang diproses.',
                'is_cancelled' => false,
                'cancelled_date' => null,
            ],
            [
                'id' => 10,
                'payer_name' => 'Global Excel',
                'patient_name' => 'Edward Gareth Andrews',
                'mrn' => '007403',
                'invoice_no' => '516340',
                'invoice_date' => '2024-09-05',
                'amount' => 5000000,
                'paid_amount' => 5000000,
                'balance' => 0,
                'due_days' => 30,
                'status' => 'PAID',
                'ref_no' => '24-JKT005',
                'courier_via' => 'JNE',
                'tracking_no' => '3578056480001',
                'sent_date' => '2024-09-08',
                'received_date' => '2024-09-12',
                'paid_on' => '2024-11-01',
                'remarks' => null,
                'is_cancelled' => false,
                'cancelled_date' => null,
            ],
            [
                'id' => 11,
                'payer_name' => 'Global Excel',
                'patient_name' => 'Christopher Parr',
                'mrn' => '062215',
                'invoice_no' => '462311',
                'invoice_date' => '2022-11-28',
                'amount' => 700000,
                'paid_amount' => 700000,
                'balance' => 0,
                'due_days' => 30,
                'status' => 'PAID',
                'ref_no' => '21-JKT044811',
                'courier_via' => 'JNE',
                'tracking_no' => '3532666250002',
                'sent_date' => '2023-01-19',
                'received_date' => '2023-01-25',
                'paid_on' => '2023-03-08',
                'remarks' => null,
                'is_cancelled' => false,
                'cancelled_date' => null,
            ],
            // --- CANCELLED (old, balance already zeroed) ---
            [
                'id' => 12,
                'payer_name' => 'Admedika',
                'patient_name' => 'Robert Wilson',
                'mrn' => '009992',
                'invoice_no' => '555100',
                'invoice_date' => '2025-10-15',
                'amount' => 2000000,
                'paid_amount' => 0,
                'balance' => 2000000,
                'due_days' => 0,
                'status' => 'BATCHING',
                'ref_no' => null,
                'courier_via' => null,
                'tracking_no' => null,
                'sent_date' => null,
                'received_date' => null,
                'paid_on' => null,
                'remarks' => 'Dibatalkan karena double entry.',
                'is_cancelled' => true,
                'cancelled_date' => '2025-11-01',
            ],
        ];

        // Auto-zero balance logic for cancelled invoices
        // Rule: if cancelled and today >= 5th of the month after cancelled_date, balance = 0
        $today = Carbon::now();
        foreach ($dummyInvoices as &$inv) {
            if ($inv['is_cancelled'] && $inv['cancelled_date']) {
                $cancelDate = Carbon::parse($inv['cancelled_date']);
                // The "zeroing deadline" is the 5th of the next month from cancel date
                $zeroDate = $cancelDate->copy()->addMonth()->startOfMonth()->addDays(4); // 5th day
                if ($today->gte($zeroDate)) {
                    $inv['balance'] = 0;
                }
            }
        }
        unset($inv);

        return view('track.index', compact('dummyInvoices'));
    }
}
